services:
  backend:
    image: ijas9118/nexus-backend-image
    pull_policy: always
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - redis
      - loki
    networks:
      - app-network

  nginx:
    image: ijas9118/nexus-nginx-image
    pull_policy: always
    container_name: nexus-nginx
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "443:443"
      - "80:80"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    networks:
      - app-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    volumes:
      - loki-data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - app-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - loki
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    networks:
      - app-network

volumes:
  redis-data:
  loki-data:
  grafana-data:

networks:
  app-network:
    driver: bridge
