services:
  backend:
    image: ijas9118/nexus-backend-image
    # container_name: nexus-backend
    pull_policy: always
    build:
      platforms: 
        - linux/amd64
      context: ./backend
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - redis
    networks:
      - app-network

  nginx:
    image: ijas9118/nexus-nginx-image
    container_name: nexus-nginx
    pull_policy: never
    build:
      platforms: 
        - linux/amd64
      context: ./frontend
      dockerfile: Dockerfile.prod
      target: prod
    ports:
      - "80:80"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    networks:
      - app-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network

volumes:
  redis-data:

networks:
  app-network:
    driver: bridge