export const MESSAGES = {
  AUTH_MESSAGES: {
    USER_EXISTS: "User already exists",
    OTP_SENT: "OTP sent to email. Please verify within 15 minutes.",
    OTP_RESENT: "New OTP sent to your email.",
    OTP_INVALID: "Invalid or expired OTP.",
    REGISTER_SUCCESS: "User registered successfully.",
    LOGIN_SUCCESS: "Logged in successfully.",
    USER_BLOCKED: "User is blocked",
    LOGOUT_SUCCESS: "Logged out successfully.",
    PASSWORD_RESET_LINK_SENT: "Password reset link sent to your email.",
    PASSWORD_UPDATED: "Password updated successfully.",
    REFRESH_TOKEN_MISSING: "Refresh token not found",
    REFRESH_TOKEN_INVALID: "Invalid token",
    USER_NOT_FOUND: "User not found",
    MENTOR_NOT_FOUND: "Mentor profile not found",
    GOOGLE_EMAIL_MISSING: "No email provided by Google",
    GITHUB_EMAIL_MISSING: "No email provided by GitHub",
    INVALID_PASSWORD: "Invalid password",
    OTP_FETCH_FAILED: "Failed to send OTP. Please try again later.",
    OTP_EXPIRED_OR_NOT_FOUND: "OTP expired or not found. Please register again.",
    OTP_EXPIRED_OR_INVALID: "OTP expired or invalid.",
  },
  ADMIN_MESSAGES: {
    // Auth
    LOGIN_SUCCESS: "success",
    INVALID_CREDENTIALS: "Invalid email or password",
    LOGOUT_SUCCESS: "Logged out successfully.",
    ACCESS_TOKEN_MISSING: "Access token not found",
    ACCESS_TOKEN_INVALID: "Invalid or expired access token",

    // User management
    USER_NOT_FOUND: "User not found",
    USER_BLOCKED: "User blocked successfully",
    USER_UNBLOCKED: "User unblocked successfully",
  },
  BOOKING_MESSAGES: {
    AUTH_REQUIRED: "Authentication required",
    BOOKING_NOT_FOUND: "Booking not found or access denied",
    UPCOMING_FETCH_SUCCESS: "Upcoming bookings fetched successfully",
    COMPLETED_FETCH_SUCCESS: "Completed bookings fetched successfully",
    RESCHEDULE_FIELDS_REQUIRED: "timeSlotId and bookingDate are required.",
    INVALID_DATE_FORMAT:
      "Invalid bookingDate format. Use ISO 8601 (e.g., \"2025-05-10T00:00:00.000Z\").",
    RESCHEDULE_SUCCESS: "Booking rescheduled successfully",
    INVALID_FILTER_DATE: "Invalid date format. Use ISO 8601 (e.g., \"2025-05-10T00:00:00.000Z\").",
    FILTER_SUCCESS: "Filtered bookings fetched successfully",
    CONFIRM_SUCCESS: "Booking confirmed successfully",
    CANNOT_RESCHEDULE_COMPLETED: "Cannot reschedule a completed booking.",
    TIME_SLOT_NOT_FOUND: "Time slot not found.",
    TIME_SLOT_ALREADY_BOOKED: "Time slot is already booked.",
    PAST_DATE_RESCHEDULE: "Cannot reschedule to a past date.",
    UPDATE_FAILED: "Failed to update booking.",
    ONLY_PENDING_CONFIRM: "Only pending bookings can be confirmed.",
    CONFIRM_FAILED: "Failed to confirm booking.",
    SLOT_NOT_FOUND_OR_BOOKED: "Time slot not found or cannot be deleted (already booked).",
    SLOT_NOT_BELONG_TO_MENTOR: "Time slot does not belong to the specified mentor.",
    SLOT_UPDATE_FAILED: "Failed to update the time slot.",
    SLOT_NOT_AVAILABLE: "Selected time slot is not available",
    RESERVE_FAILED: "Failed to reserve time slot",
    MISSING_SESSION_DETAILS: "Missing required metadata or session details",
    SLOT_EXPIRED: "Time slot is no longer available",
  },
  SEARCH_MESSAGES: {
    QUERY_REQUIRED: "Query required",
    SEARCH_FAILED: "Search failed",
  },
  NOTIFICATION_MESSAGES: {
    NOT_FOUND: "Notification not found",
    DELETED: "Notification deleted",
    PROVIDE_IDS: "Provide an array of notification IDs",
    TYPE_NOT_FOUND: "Notification type not found or is inactive",
    INVALID_TYPE: "Invalid or inactive notification type",
    TYPE_EXISTS: "Notification type with this name already exists",
  },
  CHAT_MESSAGES: {
    CONNECTION_REQUIRED: "Users must be connected to start a chat",
    FETCH_FAILED: "Failed to fetch populated chat",
    NOT_CONNECTED_TO: "User is not connected to:",
    MESSAGE_NOT_FOUND: "Message not found",
    DELETE_ONLY_SENDER: "Only the sender can delete a message",
    CHAT_ACCESS_DENIED: "User does not have access to this chat",
    GROUP_ACCESS_DENIED: "User does not have access to this group",
    NO_LONGER_CONNECTED: "Cannot send message. You are no longer connected with this user.",
  },
  CONTENT_MESSAGES: {
    CREATED: "Content created successfully",
    NOT_FOUND: "Content not found",
    VERIFIED: "Content verified successfully",
    ID_REQUIRED: "Content ID is required",
    ID_TEXT_REQUIRED: "Content ID and text are required",
  },
  BOOKMARK_MESSAGES: {
    AUTH_REQUIRED: "User is not authenticated",
    // Adding existing booking messages that are similar
    BOOKING_NOT_FOUND: "Booking not found or access denied",
  },
  CATEGORY_MESSAGES: {
    NAME_REQUIRED: "Category name is required",
    ID_NAME_REQUIRED: "Category ID and new name are required",
    NOT_FOUND: "Category not found",
    ID_REQUIRED: "Category ID is required",
    NONE_FOUND: "No categories found",
    EXISTS: "Category already exists",
  },
  COMMENT_MESSAGES: {
    CREATE_FAILED: "Failed to create comment",
  },
  REVIEW_MESSAGES: {
    AUTH_REQUIRED: "Authentication required",
    RATING_MENTOR_REQUIRED: "Rating and mentorId are required",
    CREATED: "Review created successfully",
    NOT_FOUND: "Review not found",
    UPDATED: "Review updated successfully",
    DELETED: "Review deleted successfully",
    ALREADY_REVIEWED: "You have already reviewed this mentor",
    INVALID_RATING: "Rating must be between 0.5 and 5 in increments of 0.5",
    SELF_REVIEW: "You cannot review yourself",
    INVALID_ID: "Invalid review ID",
    INVALID_PAGINATION: "Invalid pagination parameters",
    INVALID_MENTOR_ID: "Invalid mentor ID",
    UPDATE_OWN_ONLY: "You can only update your own reviews",
    DELETE_OWN_ONLY: "You can only delete your own reviews",
    INVALID_MENTOR_USER_ID: "Invalid mentor or user ID",
  },
  SQUAD_MESSAGES: {
    EXISTS: "Squad with this name already exists",
    INVALID_LIMIT: "Invalid limit value",
    INVALID_PAGE: "Invalid page value",
    NOT_FOUND: "Squad not found",
    CATEGORY_REQUIRED: "Category is required",
    USER_ID_REQUIRED: "User ID is required",
    JOIN_SUCCESS: "Successfully joined squad",
    LEAVE_SUCCESS: "Successfully left squad",
    HANDLE_REQUIRED: "Squad handle is required",
    ID_REQUIRED: "Squad ID is required",
    INVALID_CATEGORY: "Invalid category provided",
    NOT_A_MEMBER: "User is not a member of this squad",
  },
  MENTOR_MESSAGES: {
    META_NOT_FOUND: "Metadata not found",
    MISSING_FIELDS: "Missing required fields: personalInfo, experience, or mentorshipDetails.",
    MISSING_PERSONAL_INFO: "Missing required personalInfo fields: firstName, lastName, or email.",
    TARGET_AUDIENCE_NOT_FOUND: "Target audience not found",
    MENTOR_ID_REQUIRED: "Mentor ID is required.",
    DATE_START_TIME_REQUIRED: "Date and start time are required.",
    DATE_REQUIRED: "Date is required.",
    WITHDRAWAL_REJECTED: "Withdrawal request rejected",
    INVALID_META_TYPE: "Invalid metadata type",
    ALREADY_APPLIED: "You have already applied to be a mentor.",
    APPLICATION_NOT_FOUND: "Mentor application not found.",
    INVALID_USER_ID: "Invalid userId format.",
    EXPERIENCE_UPDATE_FAILED: "Failed to update mentor experience.",
    DETAILS_UPDATE_FAILED: "Failed to update mentorship details.",
    TYPE_EXISTS: "Mentorship type with this name already exists",
    TYPE_NOT_FOUND: "Mentorship type not found",
    UPDATE_INACTIVE_TYPE: "Cannot update inactive or non-existent mentorship type",
    PRICE_NEGATIVE: "Price cannot be negative",
    AUDIENCE_EXISTS: "Target audience with this name already exists",
    REGISTERED_MENTOR_REQUIRED: "Mentor not found. Please make sure you are a registered mentor.",
    INVALID_TIME_FORMAT: "Invalid start time format. Use hh:mm AM/PM.",
    PAST_SLOT: "Cannot create a time slot in the past.",
    SLOT_OVERLAP: "Time slot overlaps with an existing slot.",
    SLOT_TOO_CLOSE: "Time slot is too close to an existing slot (must be at least 1 hour before).",
    SLOT_END_OVERLAP: "Time slot’s end time overlaps with an existing slot.",
    SLOT_CONFLICT: "Time slot conflicts with an existing slot.",
  },
  PAYMENT_MESSAGES: {
    PLAN_NOT_FOUND: "Plan not found",
    PLAN_DELETED: "Plan deleted successfully",
    NO_SUBSCRIPTION: "No active subscription found.",
    WITHDRAWAL_SUBMITTED: "Withdrawal request submitted",
    ALREADY_SUBSCRIBED: "User is already subscribed to this plan with an active subscription.",
    UNKNOWN_SESSION_TYPE: "Unknown checkout session type",
    PLAN_EXISTS: "Plan with this tier already exists",
    INTERVAL_REQUIRED: "Interval is required",
  },
  WALLET_MESSAGES: {
    NOT_FOUND: "Wallet not found",
    INSUFFICIENT_BALANCE: "Insufficient balance",
    INSUFFICIENT_POINTS: "Insufficient nexus points",
    WITHDRAWAL_NOT_FOUND: "Withdrawal request not found",
    REQUEST_PROCESSED: "Request already processed",
  },
  USER_MESSAGES: {
    NOT_FOUND: "User not found",
    // Connections
    SEARCH_TERM_REQUIRED: "Search term is required",
    SEARCH_TERM_EMPTY: "Search term cannot be empty after sanitization",
    RECIPIENT_ID_REQUIRED: "Recipient ID is required",
    ALREADY_SENT: "Connection request already sent",
    ALREADY_CONNECTED: "You are already connected with this user",
    SELF_REQUEST: "Cannot send connection request to yourself",
    REQUEST_SENT: "Connection request sent successfully",
    REQUESTER_ID_REQUIRED: "Requester ID is required",
    ACCEPT_FAILED: "Failed to accept connection request",
    REJECT_FAILED: "Failed to reject connection request",
    REQUEST_REJECTED: "Connection request rejected",
    WITHDRAW_FAILED: "Failed to withdraw connection request",
    CONNECTION_ID_REQUIRED: "Connection ID is required",
    REMOVE_FAILED: "Failed to remove connection",
    REMOVED: "Connection removed successfully",

    // Followers
    FOLLOWED_ID_REQUIRED: "Followed user ID is required",
    ALREADY_FOLLOWING: "Already following this user",
    FOLLOW_SUCCESS: "Followed successfully",
    NOT_FOLLOWING: "Not following this user",
    UNFOLLOW_SUCCESS: "Unfollowed successfully",
    USER_ID_REQUIRED: "User ID is required",
    MISSING_PARAMS: "Missing required query parameters",

    // History
    HISTORY_REMOVE_FAILED: "Failed to remove from history",
    HISTORY_REMOVED: "Removed from history",
    HISTORY_FETCH_FAILED: "Failed to fetch history",

    // User Profile
    UNAUTHORIZED: "Unauthorized",
    PASSWORD_UPDATED: "Password updated successfully",
    NO_FILE: "No file uploaded",
    USERNAME_REQUIRED: "Username is required",
    PASSWORD_MISMATCH: "New password and confirm password do not match",
    INCORRECT_PASSWORD: "Current password is incorrect",
  },
  COMMON_MESSAGES: {
    SUCCESS: "success",
    MISSING_SESSION_ID: "Missing sessionId",
    UNEXPECTED_ERROR: "An unexpected error occurred.",
  },
};
